#! /bin/bash

mkdir -p styles/vendor/foundation
if mv node_modules/zurb-foundation-5/scss styles/vendor/foundation; then
  rm -rf node_modules/zurb-foundation-5
else
  rm -rf styles/vendor/foundation
  mkdir -p styles/vendor/foundation
  mv node_modules/zurb-foundation-5/scss styles/vendor/foundation
  rm -rf node_modules/zurb-foundation-5
fi

mkdir -p styles/vendor/utility-belt
if mv node_modules/utility-belt/scss styles/vendor/utility-belt; then
  rm -rf node_modules/utility-belt
else
  rm -rf styles/vendor/utility-belt
  mkdir -p styles/vendor/utility-belt
  mv node_modules/utility-belt/scss styles/vendor/utility-belt
  rm -rf node_modules/utility-belt
fi

mkdir -p styles/vendor/slick
if mv node_modules/slick-carousel/slick styles/vendor/slick; then
  rm -rf node_modules/slick-carousel
else
  rm -rf styles/vendor/slick
  mkdir -p styles/vendor/slick
  mv node_modules/slick-carousel/slick styles/vendor/slick
  rm -rf node_modules/slick-carousel
fi
