#! /bin/bash

sudo chown -R $(whoami) ~/.npm

npm install -g gulp-eslint
npm install -g gulp-browserify
npm install -g gulp-concat
npm install -g gulp-sass
npm install -g gulp-autoprefixer
npm install -g gulp-minify-css
npm install -g gulp-rename
npm install -g gulp-uglify
npm install -g gulp

link-global